services:
  mudlet:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    container_name: mudlet_dev
    volumes:
      - ../build:/home/mudlet/build:rw
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes: 
  ../build:
