services:
  mudlet: &base-settings
    image: mudlet:dev
    build:
      dockerfile: docker/Dockerfile
      context: ..
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - ../build:/home/mudlet/build:rw
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes: 
  ../build:
